In [10]:
v = [1; 19; 33]
v = [1 19 33]

1×3 Array{Int64,2}:
 1  19  33

In [11]:
v = [x^2 for x in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [12]:
filter(x -> x < 10,  v)

3-element Array{Int64,1}:
 1
 4
 9

In [14]:
v[v.<10]

3-element Array{Int64,1}:
 1
 4
 9

In [16]:
f(x) = 4x^2 + 3x*√x

f (generic function with 1 method)

In [21]:
xv = rand(10)

10-element Array{Float64,1}:
 0.9741389442708768  
 0.3191822035025871  
 0.7219021471613123  
 0.35352553259944    
 0.031104018414543244
 0.8262204111302407  
 0.1318635438416762  
 0.4754455325224043  
 0.06042457195018991 
 0.8165054977704178  

In [22]:
v = map(x->f(x),xv)

10-element Array{Float64,1}:
 6.680167648489469   
 0.948486684683349   
 3.9246595263282265  
 1.1305189816274366  
 0.02032666311580926 
 4.983581123844532   
 0.2132028828420895  
 1.887689394584544   
 0.059164150967484064
 4.880125008803055   

In [23]:
v = f.(xv)

10-element Array{Float64,1}:
 6.680167648489469   
 0.948486684683349   
 3.9246595263282265  
 1.1305189816274366  
 0.02032666311580926 
 4.983581123844532   
 0.2132028828420895  
 1.887689394584544   
 0.059164150967484064
 4.880125008803055   

In [28]:
v2 = rand(10)

10-element Array{Float64,1}:
 0.8740538428174336  
 0.3819350331507554  
 0.5904702691853663  
 0.39542613051408315 
 0.14096029677669208 
 0.006044838957984577
 0.5063038406351623  
 0.07646791842088696 
 0.6701136847139386  
 0.317708177530557   

In [34]:
v .* v2
v * v2'

10×10 Array{Float64,2}:
 5.83883    2.55139     3.94444    …  0.510819    4.47647    2.12234   
 0.829028   0.36226     0.560053      0.0725288   0.635594   0.301342  
 3.43036    1.49896     2.31739       0.300111    2.62997    1.2469    
 0.988134   0.431785    0.667538      0.0864484   0.757576   0.359175  
 0.0177666  0.00776346  0.0120023     0.00155434  0.0136212  0.00645795
 4.35592    1.9034      2.94266    …  0.381084    3.33957    1.58332   
 0.186351   0.0814297   0.12589       0.0163032   0.14287    0.0677363 
 1.64994    0.720975    1.11462       0.144348    1.26497    0.599734  
 0.0517127  0.0225969   0.0349347     0.00452416  0.0396467  0.0187969 
 4.26549    1.86389     2.88157       0.373173    3.27024    1.55046   

matrix

In [41]:
m = [1 2 7; 4 5 5; 9 8 4;]

3×3 Array{Int64,2}:
 1  2  7
 4  5  5
 9  8  4

In [38]:
I(4)
convert(Array{Float64},I(4))

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [39]:
zeros(4,4)

4×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [40]:
ones(4,4)

4×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [45]:
m = Symmetric(randn(4,4))

4×4 Symmetric{Float64,Array{Float64,2}}:
  0.735789  -0.807201  -0.183957   1.1929  
 -0.807201   0.503644  -0.394206   0.780922
 -0.183957  -0.394206  -0.0337045  0.263597
  1.1929     0.780922   0.263597   1.25655 

In [52]:
issymmetric(m)
issymmetric(rand(4,4))

false